config/routes.rb
DKSSOQ::Application.routes.draw do

  resources :subconsultants


  resources :proposals


  resources :users

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "proposals#new"

  resources :sessions

  match '*a', :to => 'application#routingError' #Catch all for routing errors, needs to be at the bottom of the routes file
  
end

app/models/subconsultant.rb
class Subconsultant < ActiveRecord::Base
  attr_accessible :contact_address, :contact_email, :contact_fax, :contact_name, :contact_phone, :firm_name, :sub_num, :proposal_id
  belongs_to :proposal
end

app/controllers/subconsultants_controller.rb
class SubconsultantsController < ApplicationController
  # GET /subconsultants
  # GET /subconsultants.json
  def index
    @subconsultants = Subconsultant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subconsultants }
    end
  end

  # GET /subconsultants/1
  # GET /subconsultants/1.json
  def show
    @subconsultant = Subconsultant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subconsultant }
    end
  end

  # GET /subconsultants/new
  # GET /subconsultants/new.json
  def new
    @subconsultant = Subconsultant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subconsultant }
    end
  end

  # GET /subconsultants/1/edit
  def edit
    @subconsultant = Subconsultant.find(params[:id])
  end

  # POST /subconsultants
  # POST /subconsultants.json
  def create
    @subconsultant = Subconsultant.new(params[:subconsultant])

    respond_to do |format|
      if @subconsultant.save
        format.html { redirect_to @subconsultant, notice: 'Subconsultant was successfully created.' }
        format.json { render json: @subconsultant, status: :created, location: @subconsultant }
      else
        format.html { render action: "new" }
        format.json { render json: @subconsultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subconsultants/1
  # PUT /subconsultants/1.json
  def update
    @subconsultant = Subconsultant.find(params[:id])

    respond_to do |format|
      if @subconsultant.update_attributes(params[:subconsultant])
        format.html { redirect_to @subconsultant, notice: 'Subconsultant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subconsultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subconsultants/1
  # DELETE /subconsultants/1.json
  def destroy
    @subconsultant = Subconsultant.find(params[:id])
    @subconsultant.destroy

    respond_to do |format|
      format.html { redirect_to subconsultants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subconsultants_helper.rb
module SubconsultantsHelper
end

app/views/subconsultants/_form.html.erb
<%= form_for(@subconsultant) do |f| %>
  <% if @subconsultant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subconsultant.errors.count, "error") %> prohibited this subconsultant from being saved:</h2>

      <ul>
      <% @subconsultant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firm_name %><br />
    <%= f.text_field :firm_name %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br />
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :contact_address %><br />
    <%= f.text_area :contact_address %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br />
    <%= f.text_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :contact_fax %><br />
    <%= f.text_field :contact_fax %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br />
    <%= f.text_field :contact_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subconsultants/edit.html.erb
<h1>Editing subconsultant</h1>

<%= render 'form' %>

<%= link_to 'Show', @subconsultant %> |
<%= link_to 'Back', subconsultants_path %>

app/views/subconsultants/index.html.erb
<h1>Listing subconsultants</h1>

<table>
  <tr>
    <th>Firm name</th>
    <th>Contact name</th>
    <th>Contact address</th>
    <th>Contact phone</th>
    <th>Contact fax</th>
    <th>Contact email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subconsultants.each do |subconsultant| %>
  <tr>
    <td><%= subconsultant.firm_name %></td>
    <td><%= subconsultant.contact_name %></td>
    <td><%= subconsultant.contact_address %></td>
    <td><%= subconsultant.contact_phone %></td>
    <td><%= subconsultant.contact_fax %></td>
    <td><%= subconsultant.contact_email %></td>
    <td><%= link_to 'Show', subconsultant %></td>
    <td><%= link_to 'Edit', edit_subconsultant_path(subconsultant) %></td>
    <td><%= link_to 'Destroy', subconsultant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subconsultant', new_subconsultant_path %>

app/views/subconsultants/new.html.erb
<h1>New subconsultant</h1>

<%= render 'form' %>

<%= link_to 'Back', subconsultants_path %>

app/views/subconsultants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firm name:</b>
  <%= @subconsultant.firm_name %>
</p>

<p>
  <b>Contact name:</b>
  <%= @subconsultant.contact_name %>
</p>

<p>
  <b>Contact address:</b>
  <%= @subconsultant.contact_address %>
</p>

<p>
  <b>Contact phone:</b>
  <%= @subconsultant.contact_phone %>
</p>

<p>
  <b>Contact fax:</b>
  <%= @subconsultant.contact_fax %>
</p>

<p>
  <b>Contact email:</b>
  <%= @subconsultant.contact_email %>
</p>


<%= link_to 'Edit', edit_subconsultant_path(@subconsultant) %> |
<%= link_to 'Back', subconsultants_path %>