config/routes.rb
DKSSOQ::Application.routes.draw do

  resources :subconsultants


  resources :proposals


  resources :users

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "proposals#new"

  resources :sessions

  match '*a', :to => 'application#routingError' #Catch all for routing errors, needs to be at the bottom of the routes file
  
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = Proposal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proposals }
    end
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
    @proposal = Proposal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proposal }
    end
  end

  # GET /proposals/new
  # GET /proposals/new.json
  def new
    @proposal = Proposal.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proposal }
    end
  end

  # GET /proposals/1/edit
  def edit
    @proposal = Proposal.find(params[:id])
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(params[:proposal])

    respond_to do |format|
      if @proposal.save
        DkssoqMailer.proposal_email(@proposal).deliver
        format.html { redirect_to root_path, notice: 'Proposal was successfully created.' }
        format.json { render json: @proposal, status: :created, location: @proposal }
      else
        format.html { render action: "new" }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proposals/1
  # PUT /proposals/1.json
  def update
    @proposal = Proposal.find(params[:id])

    respond_to do |format|
      if @proposal.update_attributes(params[:proposal])
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy

    respond_to do |format|
      format.html { redirect_to proposals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_subconsultant_fields.html.erb
<div class="dynamic_sub">
  <div class="row">
  	<div class="span4">
  	  <div class="span1">
  	  	Sub #
  	  </div>
  	  <div class="span2">
  	  	<%= f.text_field :sub_num %>
  	  </div>
  	</div>
  	<div class="span7">
  	  <div class="span2">
  	  	Firm Name
  	  </div>
  	  <div class="span4">
  	  	<%= f.text_field :firm_name %>
  	  </div>
  	</div>
  </div>

  <div class="row">
  	<div class="span4">
  	  <div class="span1">
  	  	Contact Name
  	  </div>
  	  <div class="span2">
  	  	<%= f.text_field :contact_name %>
  	  </div>
  	</div>
  	<div class="span7">
  	  <div class="span2">
  	  	Contact Address
  	  </div>
  	  <div class="span4">
  	  	<%= f.text_area :contact_address %>
  	  </div>
  	</div>
  </div>

  <div class="row">
  	<div class="span3">
  	  	Phone: 
  	  	<%= f.text_field :contact_phone, :style => 'width:150px;' %>
  	</div>
  	<div class="span4">
  	  	Fax: 
  	  	<%= f.text_field :contact_fax, :style => 'width:150px;' %>
  	</div>
  	<div class="span4">
  	  	Email:
  	  	<%= f.text_field :contact_email, :style => 'width:150px;' %>
  	</div>
  </div>

  <div class="row">
  	<div class="btn btn-danger">
  	  <%= link_to_remove_fields "Remove Subconsultant", f %>
    </div>
  </div>
</div>

app/views/proposals/edit.html.erb
<h1>Editing proposal</h1>

<%= render 'form' %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/new.html.erb
<div class="bordered_wrapper row">
  <h3>
    PROPOSAL / SOQ PREPARATION PLAN
  </h3>

  <%= render 'form' %>
</div>